services:

  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: unless-stopped

    environment:
      MARIADB_ROOT_PASSWORD: admin123
      MARIADB_DATABASE: backend
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin123

    ports:
      - "3306:3306"

    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped

    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306

    ports:
      - "8080:80"

    depends_on:
      - mariadb

volumes:
  mariadb_data: